services:
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_USER: 'toningas'
      MYSQL_PASSWORD: 'admin123'
      MYSQL_DATABASE: 'daily_diet'
      MYSQL_ROOT_PASSWORD: 'admin123'
    ports:
      - "3306:3306"
    expose:
      # Opens port 3306 on the container
      - '3306'
    volumes:
      - C:\Users\lukas\OneDrive\Área de Trabalho\Rocketseat\mysql_diet:/var/lib/mysql